name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker build
      uses: docker/setup-buildx-action@v2.4.1
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: lorenzocoracini
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push:  true
        tags: lorenzocoracini/go_ci:${{github.ref_name}}
